spring.application.name=Ecommerce-proj
spring.datasource.url=jdbc:h2:mem:sunshine
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=vignesh
spring.datasource.password=95627
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
# Overrides Jackson deserializer settings to allow null values without throwing an exception
spring.jackson.deserialization.fail-on-null-for-primitives=false
