spring.application.name=Ecommerce-proj
spring.datasource.url=jdbc:h2:file:./data/sunshine;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=vignesh
spring.datasource.password=95627
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
spring.h2.console.enabled=true
spring.jackson.deserialization.fail-on-null-for-primitives=false